[GruvboxDark.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec08c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[GruvboxDark.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[GruvboxDark.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec08c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[env]
TERM = "xterm-256color"

[font]
size = 7

[font.bold]
family = "SF Mono"

[font.italic]
family = "SF Mono"

[font.normal]
family = "SF Mono"
style = "Regular"

[scrolling]
history = 10000

[window]
dynamic_padding = false
opacity = 0.95

[window.padding]
x = 4
y = 4
