
[env]
TERM = "xterm-256color"

[font]
size = 15
normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Italic" }
bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }

[general]
import = [
  "~/.config/alacritty/themes/one_dark.toml"
]
